# Generated by Django 5.2.8 on 2025-11-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Укажите название книги')),
                ('image', models.ImageField(upload_to='books/', verbose_name='Загрузите обложку')),
                ('description', models.TextField(verbose_name='Укажите аннотацию')),
                ('director', models.CharField(default='неизвестен', max_length=100, verbose_name='Укажите автора книги')),
                ('genre', models.CharField(choices=[('Фантастика', 'Фантастика'), ('Ужасы', 'Ужасы'), ('Драма', 'Драма'), ('Роман', 'Роман'), ('Фэнтези', 'Фэнтези'), ('История', 'История')], max_length=100, verbose_name='Укажите жанр')),
                ('country', models.CharField(default='Кыргызстан', max_length=100, verbose_name='Укажите страну')),
                ('pages', models.PositiveIntegerField(default=400, verbose_name='Укажите количество страниц')),
                ('age', models.PositiveIntegerField(default=8, verbose_name='Укажите возрастное ограничение')),
                ('language', models.CharField(max_length=100, verbose_name='Укажите язык написания')),
                ('publishing_house', models.CharField(max_length=100, verbose_name='Укажите издательство')),
            ],
        ),
    ]
