# Generated by Django 5.2.8 on 2025-11-08 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rewiew'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='age',
            field=models.PositiveIntegerField(default=8, verbose_name='Возрастное ограничение'),
        ),
        migrations.AlterField(
            model_name='book',
            name='country',
            field=models.CharField(default='Кыргызстан', max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name='Аннотация'),
        ),
        migrations.AlterField(
            model_name='book',
            name='director',
            field=models.CharField(default='неизвестен', max_length=100, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Фантастика', 'Фантастика'), ('Ужасы', 'Ужасы'), ('Драма', 'Драма'), ('Роман', 'Роман'), ('Фэнтези', 'Фэнтези'), ('История', 'История')], max_length=100, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='books/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=100, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество страниц'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishing_house',
            field=models.CharField(max_length=100, verbose_name='Издательство'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название книги'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=4)),
                ('comments', models.TextField()),
                ('choice_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book')),
                ('name_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Rewiew',
        ),
    ]
