# Generated by Django 5.2.8 on 2025-11-21 08:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0005_alter_review_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('Карта', 'Карта'), ('Наличные', 'Наличные')], max_length=20, verbose_name='Способ оплаты')),
                ('delivery_method', models.CharField(choices=[('courier', 'Курьер'), ('pickup', 'Самовывоз')], max_length=20, verbose_name='Способ доставки')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес доставки')),
                ('telephone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Номер должен быть в формате +996 XXX XXX XXX, где X — цифра', regex='^\\+996 \\d{3} \\d{3} \\d{3}$')], verbose_name='Телефон')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Книга')),
            ],
        ),
    ]
